name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run build
      run: echo Hello, world!
    - name: Run deploy
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
